import { Game } from "@/types/game";

/**
 * Firebase bağlanana kadar kullanılacak demo oyun verileri.
 * Bu veriler GameDistribution API'sinden gelecek gerçek verilerin yapısını simüle eder.
 */
export const DEMO_GAMES: Game[] = [
  {
    id: "1",
    gameDistId: "subway-surfers-01",
    title: "Subway Surfers",
    slug: "subway-surfers",
    description: "Subway Surfers, sonsuz bir koşu oyunudur. Trenlerden kaçın, bozuk para toplayın ve yeni karakterlerin kilidini açın!",
    instructions: "Kaymak için sola/sağa kaydırın. Zıplamak için yukarı, kaymak için aşağı kaydırın.",
    category: { name: "Aksiyon", slug: "aksiyon" },
    thumbnailUrl: "https://img.gamedistribution.com/d7a529f0e0e94e39a5b6cfe4b0942e89-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["koşu", "arcade", "3d"],
    metrics: { playCount: 245000, likes: 12400 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "2",
    gameDistId: "temple-run-02",
    title: "Temple Run 2",
    slug: "temple-run-2",
    description: "Temple Run 2'de tapınaktan kaçışınıza devam edin! Yeni engeller, güçlendirmeler ve ortamlar sizi bekliyor.",
    instructions: "Kaydırarak yön değiştirin, eğilerek engellerden kaçının.",
    category: { name: "Macera", slug: "macera" },
    thumbnailUrl: "https://img.gamedistribution.com/9f47ae0890c14a72ac2c4f3cb1e8e685-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["macera", "koşu", "3d"],
    metrics: { playCount: 189000, likes: 9800 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "3",
    gameDistId: "chess-03",
    title: "Master Chess",
    slug: "master-chess",
    description: "Satranç becerilerinizi geliştirin! Yapay zekaya karşı oynayın veya arkadaşınıza meydan okuyun.",
    instructions: "Taşlarınızı sürükleyerek hareket ettirin. Rakibinizin şahına mat yapın!",
    category: { name: "Strateji", slug: "strateji" },
    thumbnailUrl: "https://img.gamedistribution.com/e1a12aa3abc04adcaf6fef00f56c605b-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["strateji", "satranç", "2-kişilik"],
    metrics: { playCount: 87000, likes: 5400 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "4",
    gameDistId: "bubble-04",
    title: "Bubble Shooter",
    slug: "bubble-shooter",
    description: "Klasik baloncuk patlatma oyunu! Aynı renkteki 3 veya daha fazla baloncuğu eşleştirin.",
    instructions: "Fare ile nişan alın ve tıklayarak baloncukları fırlatın.",
    category: { name: "Bulmaca", slug: "bulmaca" },
    thumbnailUrl: "https://img.gamedistribution.com/5a797ea3c4a54c2fae84ea875d8cfe36-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["bulmaca", "rahatlatıcı", "klasik"],
    metrics: { playCount: 156000, likes: 7200 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "5",
    gameDistId: "drift-hunters-05",
    title: "Drift Hunters",
    slug: "drift-hunters",
    description: "En iyi drift oyunu! Arabanızı özelleştirin ve drift yaparak puan kazanın.",
    instructions: "WASD veya ok tuşlarıyla araba kullanın. Space ile fren yapın.",
    category: { name: "Yarış", slug: "yaris" },
    thumbnailUrl: "https://img.gamedistribution.com/df30460e9d4e4df7af3e384ef1ae78f5-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["yarış", "araba", "drift", "3d"],
    metrics: { playCount: 203000, likes: 11200 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "6",
    gameDistId: "basketball-06",
    title: "Basketball Stars",
    slug: "basketball-stars",
    description: "Online basketbol oyunu! 1v1 maçlarda rakiplerinizi alt edin.",
    instructions: "Fare ile nişan alın ve atış yapın. WASD ile hareket edin.",
    category: { name: "Spor", slug: "spor" },
    thumbnailUrl: "https://img.gamedistribution.com/42b3a36cb1e14dbd9c22c3d48d2e27f9-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["spor", "basketbol", "multiplayer"],
    metrics: { playCount: 134000, likes: 6800 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "7",
    gameDistId: "slither-07",
    title: "Slither.io",
    slug: "slither-io",
    description: "Yılanınızı büyütün ve diğer oyuncuları alt edin! Klasik .io oyunu deneyimi.",
    instructions: "Fare ile yön verin, tıklayarak hızlanın.",
    category: { name: "IO Oyunları", slug: "io-oyunlari" },
    thumbnailUrl: "https://img.gamedistribution.com/3dd6b35eb3054417974ed0e744aaa069-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["io", "multiplayer", "yılan"],
    metrics: { playCount: 312000, likes: 15600 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "8",
    gameDistId: "coloring-08",
    title: "Happy Color",
    slug: "happy-color",
    description: "Sayılarla boyama oyunu! Rahatlatıcı ve eğlenceli boyama deneyimi.",
    instructions: "Renkleri seçin ve numaralı alanlara tıklayarak boyayın.",
    category: { name: "Boyama", slug: "boyama" },
    thumbnailUrl: "https://img.gamedistribution.com/37a5e95fd83c4e2ba68cb4f0d85c2582-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["boyama", "rahatlatıcı", "sanat"],
    metrics: { playCount: 95000, likes: 4300 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "9",
    gameDistId: "fireboy-09",
    title: "Fireboy and Watergirl",
    slug: "fireboy-and-watergirl",
    description: "İki kişilik macera oyunu! Fireboy ve Watergirl olarak bulmacaları çözün.",
    instructions: "WASD ile Watergirl'ü, ok tuşlarıyla Fireboy'u kontrol edin.",
    category: { name: "2 Kişilik", slug: "2-kisilik" },
    thumbnailUrl: "https://img.gamedistribution.com/c4bb9bf20b8f47848fbb57d34eaab555-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["2-kişilik", "macera", "bulmaca"],
    metrics: { playCount: 278000, likes: 14200 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "10",
    gameDistId: "fashion-10",
    title: "Fashion Battle",
    slug: "fashion-battle",
    description: "Moda yarışmasına katılın! En güzel kıyafetleri seçin ve yarışmayı kazanın.",
    instructions: "Kıyafetleri sürükleyerek giydirin. Aksesuarlar ekleyin.",
    category: { name: "Kız Oyunları", slug: "kiz-oyunlari" },
    thumbnailUrl: "https://img.gamedistribution.com/e0d5ee7f1ad3439eb3a3b22e87032147-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["kız", "moda", "giydirme"],
    metrics: { playCount: 167000, likes: 8900 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "11",
    gameDistId: "block-puzzle-11",
    title: "Block Puzzle",
    slug: "block-puzzle",
    description: "Tetris benzeri blok bulmaca oyunu! Blokları yerleştirin ve satırları temizleyin.",
    instructions: "Blokları sürükleyerek tahta üzerine yerleştirin.",
    category: { name: "Bulmaca", slug: "bulmaca" },
    thumbnailUrl: "https://img.gamedistribution.com/1c5cd7e26f304bd6bd28dd29e7e2f911-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["bulmaca", "blok", "tetris"],
    metrics: { playCount: 142000, likes: 6100 },
    isActive: true,
    createdAt: Date.now(),
  },
  {
    id: "12",
    gameDistId: "moto-12",
    title: "Moto X3M",
    slug: "moto-x3m",
    description: "Motosiklet engel parkuru oyunu! Tehlikeli pistlerde hız yapın ve akrobasi yapın.",
    instructions: "Yukarı ok ile gaz verin, aşağı ok ile fren yapın. Eğilmek için sol/sağ ok.",
    category: { name: "Yarış", slug: "yaris" },
    thumbnailUrl: "https://img.gamedistribution.com/4c4d25f498804c57947dca57a6dd7e83-512x512.jpeg",
    iframeUrl: "https://html5.gamedistribution.com/rvvASMiM/c988cc38c43746df9dbd25d3e3e3e4d3/index.html",
    tags: ["yarış", "motor", "engel"],
    metrics: { playCount: 198000, likes: 10300 },
    isActive: true,
    createdAt: Date.now(),
  },
];
